const preguntas =[
    { pregunta: "comun",
 respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],
 correcta: "common" },
    { pregunta: "common",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "comun" },
    { pregunta: "cada",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "each" },
    { pregunta: "each",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "cada" },
    { pregunta: "decir",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "say" },
    { pregunta: "say",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "decir" },
    { pregunta: "respuestas",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "answers" },
    { pregunta: "answers",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "respuestas" },
    { pregunta: "vamos",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "lets" },
    { pregunta: "lets",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "vamos" },
    { pregunta: "escuchar",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "listen" },
    { pregunta: "listen",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "escuchar" },
    { pregunta: "mirarObservar",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "watch" },
    { pregunta: "watch",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "mirarObservar" },
    { pregunta: "revisión",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "review" },
    { pregunta: "review",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "revisión" },
    { pregunta: "acerca de",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "about" },
    { pregunta: "about",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "acerca de" },
    { pregunta: "hablar",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "talk" },
    { pregunta: "talk",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "hablar" },
    { pregunta: "mirar",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "look" },
    { pregunta: "look",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "mirar" },
    { pregunta: "semanalmente",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "weekly" },
    { pregunta: "weekly",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "semanalmente" },
    { pregunta: "todos",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "everyone" },
    { pregunta: "everyone",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "todos" },
    { pregunta: "cómo",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "how to" },
    { pregunta: "how to",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "cómo" },
    { pregunta: "diversión",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "fun" },
    { pregunta: "fun",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "diversión" },
    { pregunta: "ha sido",
     respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "has been" },
    { pregunta: "has been",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "ha sido" },
    { pregunta: "viajeRecorrido",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "journey" },
    { pregunta: "journey",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "viajeRecorrido" },
    { pregunta: "genialExelente",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "great" },
    { pregunta: "great",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "genialExelente" },
    { pregunta: "doce",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "twelve" },
    { pregunta: "twelve",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "doce" },
    { pregunta: "trece",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "thirteen" },
    { pregunta: "thirteen",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "trece" },
    { pregunta: "veinte",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "twenty" },
    { pregunta: "twenty",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "veinte" },
    { pregunta: "treinta",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "thirty" },
    { pregunta: "thirty",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "treinta" },
    { pregunta: "vocales",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "vowels" },
    { pregunta: "vowels",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],

 correcta: "vocales" },
    { pregunta: "lunes",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "monday" },
    { pregunta: "monday",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "lunes" },
    { pregunta: "martes",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "tuesday" },
    { pregunta: "tuesday",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "martes" },
    { pregunta: "miércoles",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "wednesday" },
    { pregunta: "wednesday",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "miércoles" },
    { pregunta: "jueves",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "thursday" },
    { pregunta: "thursday",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "jueves" },
    { pregunta: "viernes",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "friday" },
    { pregunta: "friday",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "viernes" },
    { pregunta: "sábado",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "saturday" },
    { pregunta: "saturday",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "sábado" },
    { pregunta: "domingo",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "sunday" },
    { pregunta: "sunday",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "domingo" },
    { pregunta: "grabar",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "record" },
    { pregunta: "record",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "grabar" },
    { pregunta: "muy bien",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "all right" },
    { pregunta: "all right",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "muy bien" },
    { pregunta: "chicos",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "guys" },
    { pregunta: "guys",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "chicos" },
    { pregunta: "emocionado",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "excited" },
    { pregunta: "excited",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "emocionado" },
    { pregunta: "nos tuvo tenido",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "had us" },
    { pregunta: "had us",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "nos tuvo tenido" },
    { pregunta: "yendo",
         respuestas: ["common", "each", "say", "answers","lets", "listen", "watch", "review","about", "talk", "look", "weekly","everyone", "how to", "fun", "has been", "journey","great", "twelve", "thirteen", "twenty","thirty", "vowels", "monday", "tuesday","wednesday","thursday", "friday", "saturday", "sunday","record", "all right", "guys", "excited","had us","going"],

 correcta: "going" },
    { pregunta: "going",
                    respuestas: ["comun", "cada", "decir", "respuestas", "vamos", "escuchar", "mirarObservar", "revisión", "acerca de", "hablar", "mirar", "semanalmente", "todos", "cómo", "diversión", "ha sido", "viajeRecorrido", "genialExelente", "doce", "trece", "veinte", "treinta", "vocales", "lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo", "grabar", "muy bien", "chicos", "emocionado", "nos tuvo tenido", "yendo"],
 correcta: "yendo" }
];